controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller : App\Controller\HomeController::index

cart:
    path: /cart
    controller : App\Controller\CartController::index

userorders:
    path: /userorders
    controller : App\Controller\SalesOrderController::userOrders
    
add_to_cart:
    path: '/add-to-cart/{productId}'
    controller: 'App\Controller\CartController::addToCart'
    methods: ['POST']
app_homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /login
        permanent: true
